name: task_manager_app
description: "App for managing tasks"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in: ^6.2.2

  # State Management
  get: ^4.7.2
  get_storage:

  # UI
  sizer: ^2.0.15
  ionicons: 

  # Utils
  path: 
  url_launcher: 
  image_picker:
  intl:
  internet_connection_checker: 
  open_file_plus: ^3.4.1
  permission_handler: 
  file_picker:
  simple_fontellico_progress_dialog: ^0.3.0
  open_file: ^3.5.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700


